import type { ExplainedMetric, RuleOutcome, Severity } from '@/types/core';
import type { Finding, PurposeLine } from '@/types/application';
import type { CrossCheckResult } from '@/domain/calculations/cross-checks';
import type { RefinancingAnalysis } from '@/domain/calculations/bureau';
import type { RepaymentCapacityResult } from '@/domain/calculations/repayment-capacity';
import type { DataQualityResult } from './data-quality';
import type { StopFactorHit } from './stop-factors';
import { formatValue, operatorSymbol } from './policy-engine';

/**
 * Findings engine (§32) and rule-based analytical commentary (§81).
 *
 * Findings are generated deterministically from the calculation results — no
 * language model is involved. Each finding states what was observed, what was
 * expected, where the number came from and what it means for the credit.
 */

export interface FindingsInput {
  crossChecks: CrossCheckResult[];
  policyOutcomes: RuleOutcome[];
  refinancing?: RefinancingAnalysis;
  repayment?: RepaymentCapacityResult;
  dataQuality?: DataQualityResult;
  stopFactors?: StopFactorHit[];
  purposeLines?: PurposeLine[];
  requestedAmount?: number;
  /** Current vs previous ratio values for trend findings. */
  ratioTrend?: Array<{ metric: ExplainedMetric; previous: number | null }>;
  manual?: Finding[];
}

const fmt = (n: number) => new Intl.NumberFormat('az-AZ', { maximumFractionDigits: 0 }).format(Math.round(n));
const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

export function generateFindings(input: FindingsInput): Finding[] {
  const findings: Finding[] = [];
  let seq = 0;
  const id = (prefix: string) => `${prefix}-${(seq += 1).toString().padStart(3, '0')}`;

  /* ---------------- Stop factors ---------------- */
  for (const hit of (input.stopFactors ?? []).filter((h) => h.triggered)) {
    findings.push({
      id: id('SF'),
      category: 'POLICY',
      severity: 'CRITICAL',
      title: `Stop faktor: ${hit.rule.labelAz}`,
      description: hit.messageAz,
      observedValue: hit.observedValue,
      source: hit.rule.sourceRef,
      resolutionStatus: 'OPEN',
      autoGenerated: true,
    });
  }
  for (const hit of (input.stopFactors ?? []).filter((h) => h.waivedBySector)) {
    findings.push({
      id: id('SFW'),
      category: 'POLICY',
      severity: 'MEDIUM',
      title: `Sektor istisnası tətbiq edildi: ${hit.rule.labelAz}`,
      description: `Şərt pozulur, lakin ${hit.rule.waivedForSectors?.join(', ')} sektoru üzrə metodologiya istisna nəzərdə tutur. Əsaslandırma sənədləşdirilməlidir.`,
      observedValue: hit.observedValue,
      source: hit.rule.sourceRef,
      resolutionStatus: 'OPEN',
      autoGenerated: true,
    });
  }

  /* ---------------- Reconciliation ---------------- */
  for (const check of input.crossChecks.filter((c) => !c.passed)) {
    findings.push({
      id: id('CC'),
      category: check.key === 'DEBT_RECONCILIATION' ? 'CREDIT_BEHAVIOUR' : 'RECONCILIATION',
      severity: check.severity,
      title: `Uzlaşma fərqi: ${check.labelAz}`,
      description: check.interpretationAz,
      observedValue: `${fmt(check.actual)} AZN`,
      expectedValue: `${fmt(check.expected)} AZN`,
      financialImpact: Math.abs(check.difference),
      source: check.formula,
      resolutionStatus: 'OPEN',
      autoGenerated: true,
    });
  }

  /* ---------------- Policy breaches ---------------- */
  for (const outcome of input.policyOutcomes.filter((o) => !o.passed)) {
    findings.push({
      id: id('PL'),
      category: outcome.metric.includes('dscr') || outcome.metric.includes('Capacity') ? 'CASH_FLOW' : 'FINANCIAL_RISK',
      severity: outcome.severity,
      title: `Siyasət limiti pozulur: ${outcome.ruleName}`,
      description: outcome.message,
      observedValue: outcome.actual !== null ? String(outcome.actual.toFixed(2)) : '—',
      expectedValue: `${operatorSymbol(outcome.operator)} ${outcome.threshold}`,
      source: outcome.source,
      resolutionStatus: 'OPEN',
      autoGenerated: true,
    });
  }

  /* ---------------- Refinancing behaviour ---------------- */
  for (const flag of input.refinancing?.flags ?? []) {
    findings.push({
      id: id('RF'),
      category: 'CREDIT_BEHAVIOUR',
      severity: flag.severity,
      title: refinancingTitle(flag.key),
      description: flag.messageAz,
      observedValue:
        input.refinancing?.instalmentRepaymentShare !== null && input.refinancing?.instalmentRepaymentShare !== undefined
          ? `Aylıq ödənişlə bağlanma payı: ${pct(input.refinancing.instalmentRepaymentShare)}`
          : undefined,
      expectedValue: '> 50%',
      source: 'AKB çıxarışı — kredit dövriyyəsi təhlili (Metodologiya §4.7)',
      resolutionStatus: 'OPEN',
      autoGenerated: true,
    });
  }

  /* ---------------- Repayment capacity ---------------- */
  const rc = input.repayment;
  if (rc) {
    if (!rc.hasCapacity) {
      findings.push({
        id: id('RC'),
        category: 'CASH_FLOW',
        severity: 'CRITICAL',
        title: 'Ödəmə qabiliyyəti kifayət etmir',
        description: `Əməliyyatdan sonrakı aylıq borc xidməti ${fmt(rc.postTransactionDebtService)} AZN, mövcud pul axını isə ${fmt(
          rc.cfads,
        )} AZN təşkil edir. Aylıq kəsir: ${fmt(Math.abs(rc.headroomMonthly))} AZN.`,
        observedValue: `${fmt(rc.cfads)} AZN / ay`,
        expectedValue: `≥ ${fmt(rc.postTransactionDebtService)} AZN / ay`,
        financialImpact: Math.abs(rc.headroomMonthly) * 12,
        source: 'Ödəmə qabiliyyəti hesablaması (MZH Q6 / CFADS)',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    } else if (rc.dscrAfter !== null && rc.dscrAfter < 1.5 && rc.dscrAfter >= 1) {
      findings.push({
        id: id('RC'),
        category: 'CASH_FLOW',
        severity: 'HIGH',
        title: 'Borc xidməti örtüyü normadan aşağıdır',
        description: `Əməliyyatdan sonrakı DSCR ${rc.dscrAfter.toFixed(2)}x — 1.50x normasından aşağıdır. Pul axınının kiçik dalğalanması belə ödənişi riskə atır.`,
        observedValue: `${rc.dscrAfter.toFixed(2)}x`,
        expectedValue: '≥ 1.50x',
        source: 'Proqnoz pul axını',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }

    if (rc.monthlyNetProfit > 0 && rc.cfads < rc.monthlyNetProfit * 0.5) {
      findings.push({
        id: id('CF'),
        category: 'CASH_FLOW',
        severity: 'HIGH',
        title: 'Mənfəət pula çevrilmir',
        description: `Aylıq xalis mənfəət ${fmt(rc.monthlyNetProfit)} AZN olduğu halda, borc xidmətinə yönəldilə bilən pul axını yalnız ${fmt(
          rc.cfads,
        )} AZN-dir. Uçot mənfəəti eyni gücdə nağd yaratmır.`,
        observedValue: `${fmt(rc.cfads)} AZN`,
        expectedValue: `≈ ${fmt(rc.monthlyNetProfit)} AZN`,
        source: 'MZH və pul axını müqayisəsi',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }
  }

  /* ---------------- Ratio trend deterioration ---------------- */
  for (const t of input.ratioTrend ?? []) {
    const finding = trendFinding(t.metric, t.previous, id);
    if (finding) findings.push(finding);
  }

  /* ---------------- Purpose ---------------- */
  if (input.purposeLines && input.purposeLines.length > 0 && input.requestedAmount) {
    const total = input.purposeLines.reduce((s, p) => s + p.amount, 0) || input.requestedAmount;
    const nonBusiness = input.purposeLines
      .filter((p) => p.category === 'PERSONAL_NON_BUSINESS')
      .reduce((s, p) => s + p.amount, 0);
    const unsupported = input.purposeLines
      .filter((p) => p.evidence === 'MISSING' || p.evidence === 'VERBAL')
      .reduce((s, p) => s + p.amount, 0);
    const refinancing = input.purposeLines
      .filter((p) => p.category === 'REFINANCE_ATB' || p.category === 'REFINANCE_OTHER_BANK')
      .reduce((s, p) => s + p.amount, 0);

    if (nonBusiness > 0) {
      findings.push({
        id: id('PP'),
        category: 'PURPOSE',
        severity: nonBusiness / total > 0.25 ? 'HIGH' : 'MEDIUM',
        title: 'Kreditin bir hissəsi biznesdənkənar təyinatlıdır',
        description: `Tələb olunan məbləğin ${pct(nonBusiness / total)} hissəsi (${fmt(
          nonBusiness,
        )} AZN) biznesə gəlir gətirməyən təyinata yönəldilir. Bu hissə biznesin pul axını ilə ödənilməli olacaq, lakin əvəzində əlavə gəlir yaratmır.`,
        observedValue: `${fmt(nonBusiness)} AZN`,
        source: 'Kredit məqsədi bölgüsü',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }
    if (unsupported / total > 0.2) {
      findings.push({
        id: id('PP'),
        category: 'PURPOSE',
        severity: 'HIGH',
        title: 'Təyinatın əhəmiyyətli hissəsi sənədlə təsdiqlənmir',
        description: `Məbləğin ${pct(unsupported / total)} hissəsi üzrə təsdiqedici sənəd yoxdur və ya yalnız şifahi məlumat mövcuddur — məqsədli istifadəyə nəzarət məhdudlaşır.`,
        observedValue: `${fmt(unsupported)} AZN`,
        source: 'Kredit məqsədi bölgüsü',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }
    if (refinancing / total > 0.5) {
      findings.push({
        id: id('PP'),
        category: 'PURPOSE',
        severity: 'MEDIUM',
        title: 'Kredit əsasən refinansman məqsədi daşıyır',
        description: `Məbləğin ${pct(
          refinancing / total,
        )} hissəsi mövcud borcların bağlanmasına yönəldilir — biznesə yeni resurs əlavə edilmir.`,
        observedValue: `${fmt(refinancing)} AZN`,
        source: 'Kredit məqsədi bölgüsü',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }
  }

  /* ---------------- Data quality ---------------- */
  const dq = input.dataQuality;
  if (dq) {
    if (dq.grade === 'D' || dq.grade === 'E') {
      findings.push({
        id: id('DQ'),
        category: 'DATA_QUALITY',
        severity: dq.grade === 'E' ? 'CRITICAL' : 'HIGH',
        title: `Məlumat keyfiyyəti reytinqi: ${dq.grade} — ${dq.gradeLabelAz}`,
        description: `Maliyyə göstəricilərinin ${dq.verbalDependencyPct.toFixed(
          0,
        )}%-i şifahi məlumata əsaslanır və ${dq.unreconciledCount} uzlaşma yoxlaması uğursuzdur. Rəqəmlərin özündən əvvəl onlara nə dərəcədə etibar edilə biləcəyi məsələsi həll edilməlidir.`,
        observedValue: `${dq.scorePct.toFixed(0)} / 100`,
        source: 'Məlumat keyfiyyəti mühərriki',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }
    for (const f of dq.factors.filter((x) => x.score === 0 && x.weight >= 10)) {
      findings.push({
        id: id('DQ'),
        category: 'DATA_QUALITY',
        severity: 'MEDIUM',
        title: `Təsdiq mənbəyi yoxdur: ${f.labelAz}`,
        description: `${f.labelAz} üzrə heç bir təsdiqedici sənəd təqdim edilməyib (${f.evidenceSummary}).`,
        source: 'Sənəd reyestri',
        resolutionStatus: 'OPEN',
        autoGenerated: true,
      });
    }
  }

  return [...findings, ...(input.manual ?? [])].sort(
    (a, b) => severityRank(a.severity) - severityRank(b.severity),
  );
}

function severityRank(s: Severity): number {
  return { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, INFO: 4 }[s];
}

function refinancingTitle(key: string): string {
  switch (key) {
    case 'LOW_ORDINARY_AMORTISATION':
      return 'Əvvəlki kreditlər əsasən refinansmanla bağlanıb';
    case 'REPEATED_REFINANCING':
      return 'Təkrarlanan refinansman modeli';
    case 'HIGH_REFINANCING_SHARE':
      return 'Refinansman payı yüksəkdir';
    case 'SHORT_REFINANCE_GAP':
      return 'Kreditlər arasında qısa fasilə';
    case 'DEBT_EVERGREENING':
      return 'Borc yükünün davamlı artması';
    default:
      return 'Kredit davranışı üzrə qeyd';
  }
}

const TREND_RULES: Array<{
  metric: string;
  direction: 'INCREASE_BAD' | 'DECREASE_BAD';
  materialPct: number;
  severity: Severity;
  title: string;
  category: Finding['category'];
}> = [
  { metric: 'receivableDays', direction: 'INCREASE_BAD', materialPct: 0.25, severity: 'HIGH', title: 'Debitor günləri əhəmiyyətli artıb', category: 'FINANCIAL_RISK' },
  { metric: 'inventoryDays', direction: 'INCREASE_BAD', materialPct: 0.3, severity: 'MEDIUM', title: 'Ehtiyat günləri əhəmiyyətli artıb', category: 'FINANCIAL_RISK' },
  { metric: 'debtToEbitda', direction: 'INCREASE_BAD', materialPct: 0.3, severity: 'HIGH', title: 'Borc / EBITDA nisbəti pisləşib', category: 'FINANCIAL_RISK' },
  { metric: 'ebitdaMargin', direction: 'DECREASE_BAD', materialPct: 0.2, severity: 'MEDIUM', title: 'EBITDA marjası daralıb', category: 'FINANCIAL_RISK' },
  { metric: 'currentRatio', direction: 'DECREASE_BAD', materialPct: 0.2, severity: 'MEDIUM', title: 'Cari likvidlik zəifləyib', category: 'FINANCIAL_RISK' },
  { metric: 'cashConversionCycle', direction: 'INCREASE_BAD', materialPct: 0.3, severity: 'HIGH', title: 'Nağd dövriyyə tsikli uzanıb', category: 'CASH_FLOW' },
];

function trendFinding(
  metric: ExplainedMetric,
  previous: number | null,
  id: (p: string) => string,
): Finding | null {
  const rule = TREND_RULES.find((r) => r.metric === metric.key);
  if (!rule || previous === null || metric.value === null || previous === 0) return null;

  const change = (metric.value - previous) / Math.abs(previous);
  const adverse = rule.direction === 'INCREASE_BAD' ? change > rule.materialPct : change < -rule.materialPct;
  if (!adverse) return null;

  const unitFmt = (v: number) =>
    metric.unit === 'PERCENT' ? pct(v) : metric.unit === 'DAYS' ? `${v.toFixed(0)} gün` : `${v.toFixed(2)}x`;

  return {
    id: id('TR'),
    category: rule.category,
    severity: rule.severity,
    title: rule.title,
    description: `${metric.label} əvvəlki dövrdə ${unitFmt(previous)} idi, cari dövrdə ${unitFmt(
      metric.value,
    )} təşkil edir — dəyişiklik ${pct(Math.abs(change))}. Bu dinamika izah tələb edir.`,
    observedValue: unitFmt(metric.value),
    expectedValue: unitFmt(previous),
    source: metric.formula,
    resolutionStatus: 'OPEN',
    autoGenerated: true,
  };
}

/* ------------------------------------------------------------------ */
/* Rule-based analytical commentary (§81)                              */
/* ------------------------------------------------------------------ */

export interface CommentaryInput {
  ratios: Record<string, ExplainedMetric>;
  previousRatios?: Record<string, number | null>;
  salesGrowthPct?: number | null;
  ebitdaGrowthPct?: number | null;
  repayment?: RepaymentCapacityResult;
  crossChecks: CrossCheckResult[];
  refinancing?: RefinancingAnalysis;
}

/** Deterministic sentences an underwriter would otherwise type by hand. */
export function generateCommentary(input: CommentaryInput): string[] {
  const lines: string[] = [];
  const r = input.ratios;

  if (input.salesGrowthPct !== null && input.salesGrowthPct !== undefined) {
    if (input.ebitdaGrowthPct !== null && input.ebitdaGrowthPct !== undefined) {
      if (input.salesGrowthPct > 0.1 && input.ebitdaGrowthPct < input.salesGrowthPct * 0.6) {
        lines.push(
          `Satış ${pct(input.salesGrowthPct)} artdığı halda EBITDA yalnız ${pct(
            input.ebitdaGrowthPct,
          )} artıb — marja sıxılması müşahidə olunur.`,
        );
      } else if (input.salesGrowthPct > 0.1) {
        lines.push(
          `Satış ${pct(input.salesGrowthPct)}, EBITDA isə ${pct(input.ebitdaGrowthPct)} artıb — artım rentabelliyi qoruyur.`,
        );
      } else if (input.salesGrowthPct < -0.05) {
        lines.push(`Satış ${pct(Math.abs(input.salesGrowthPct))} azalıb — gəlir bazasının dayanıqlığı yoxlanılmalıdır.`);
      }
    }
  }

  const prev = input.previousRatios ?? {};
  const trend = (key: string, label: string, unit: 'DAYS' | 'TIMES' | 'PERCENT') => {
    const cur = r[key]?.value;
    const old = prev[key];
    if (cur === null || cur === undefined || old === null || old === undefined) return;
    const f = (v: number) => (unit === 'DAYS' ? `${v.toFixed(0)} gün` : unit === 'PERCENT' ? pct(v) : `${v.toFixed(2)}x`);
    if (Math.abs(cur - old) / Math.max(Math.abs(old), 0.0001) > 0.15) {
      lines.push(`${label} ${f(old)}-dən ${f(cur)}-ə dəyişib.`);
    }
  };

  trend('receivableDays', 'Debitor borcların dövretmə müddəti', 'DAYS');
  trend('inventoryDays', 'Ehtiyatların dövretmə müddəti', 'DAYS');
  trend('debtToEbitda', 'Borc / EBITDA nisbəti', 'TIMES');
  trend('currentRatio', 'Cari likvidlik əmsalı', 'TIMES');

  const rc = input.repayment;
  if (rc) {
    if (!rc.hasCapacity) {
      lines.push(
        `Bəyan edilən mənfəətliliyə baxmayaraq, əməliyyat pul axını təklif olunan strukturu dəstəkləmək üçün kifayət etmir (aylıq kəsir ${fmt(
          Math.abs(rc.headroomMonthly),
        )} AZN).`,
      );
    } else if (rc.dscrAfter !== null) {
      lines.push(
        `Əməliyyatdan sonrakı borc xidməti örtüyü ${rc.dscrAfter.toFixed(2)}x təşkil edir; aylıq ehtiyat ${fmt(
          rc.headroomMonthly,
        )} AZN-dir.`,
      );
    }
  }

  const equityCheck = input.crossChecks.find((c) => c.key === 'EQUITY_RECONCILIATION');
  if (equityCheck && !equityCheck.passed && equityCheck.difference > 0) {
    lines.push(
      `Bağlanış kapitalı bölüşdürülməmiş mənfəət və təsdiqlənmiş sahibkar qoyuluşlarının izah etdiyindən ${fmt(
        equityCheck.difference,
      )} AZN çoxdur.`,
    );
  }

  const salesCash = input.crossChecks.find((c) => c.key === 'SALES_TO_CASH');
  if (salesCash && !salesCash.passed && salesCash.difference < 0) {
    lines.push(
      `Uçot artımı eyni güclü nağd yaratmaya çevrilmir: satışdan gözlənilən daxilolmalarla faktiki daxilolmalar arasında ${fmt(
        Math.abs(salesCash.difference),
      )} AZN fərq var.`,
    );
  }

  const ref = input.refinancing;
  if (ref?.instalmentRepaymentShare !== null && ref?.instalmentRepaymentShare !== undefined) {
    if (ref.instalmentRepaymentShare <= 0.5) {
      lines.push(
        `Əvvəlki kreditlərin yalnız ${pct(
          ref.instalmentRepaymentShare,
        )} hissəsi aylıq ödənişlərlə bağlanıb — qalan hissə yeni kreditlər hesabına örtülüb.`,
      );
    }
  }

  return lines;
}
